ROBOT_HOST=PiCarX
ROBOT_USER=arvydas
REMOTE_STAGE_DIR=/home/arvydas/stage3_picarx_base_hw

STEERING_CENTER=0
STEERING_LEFT_LIMIT=-20
STEERING_RIGHT_LIMIT=20

MOTOR_TEST_SPEED=20
MOTOR_TEST_DURATION_SEC=1.5

DRIVE_TEST_SPEED=18
DRIVE_TEST_FORWARD_SEC=1.2
DRIVE_TEST_BACKWARD_SEC=1.0

ENABLE_GROUND_TEST=false