ekf_filter_node:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu

    # tvarka:
    # x, y, z,
    # roll, pitch, yaw,
    # vx, vy, vz,
    # vroll, vpitch, vyaw,
    # ax, ay, az
    imu0_config: [
      false, false, false,
      false, false, true,
      false, false, false,
      false, false, true,
      false, false, false
    ]

    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: false

    transform_time_offset: 0.0
    transform_timeout: 0.0

    debug: false
    print_diagnostics: true
